//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Data
{

    public partial class Service : XPObject
    {
        string fNom;
        public string Nom
        {
            get { return fNom; }
            set { SetPropertyValue<string>(nameof(Nom), ref fNom, value); }
        }
        [Association(@"SalarieReferencesService")]
        public XPCollection<Salarie> Salaries { get { return GetCollection<Salarie>(nameof(Salaries)); } }
    }

}
