//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Data
{

    public partial class Utilisateur : XPObject
    {
        string fIdentifiant;
        public string Identifiant
        {
            get { return fIdentifiant; }
            set { SetPropertyValue<string>(nameof(Identifiant), ref fIdentifiant, value); }
        }
        string fMotDePasse;
        public string MotDePasse
        {
            get { return fMotDePasse; }
            set { SetPropertyValue<string>(nameof(MotDePasse), ref fMotDePasse, value); }
        }
        bool fAdmin;
        public bool Admin
        {
            get { return fAdmin; }
            set { SetPropertyValue<bool>(nameof(Admin), ref fAdmin, value); }
        }
    }

}
